/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemaFloricultura.apresentacao;

import br.com.sistemaFloricultura.BO.ProdutoTipoFornecedorBO;
import static br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm.deletarRowsTabela;
import static br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm.getModelo;
import br.com.sistemaFloricultura.entidade.Mensagem;
import br.com.sistemaFloricultura.entidade.Produto;
import br.com.sistemaFloricultura.entidade.ProdutoTipoFornecedorJOIN;
import br.com.sistemaFloricultura.excecao.LinhaSelectionException;
import br.com.sistemaFloricultura.excecao.SistemaFloriculturaException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm.adicionarItemsTblItemVendas;
import static br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm.verificarCodigo;
import br.com.sistemaFloricultura.excecao.QtdeUnitarioException;
import static br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm.atualizarTxtTotalVenda;

/**
 *
 * @author josemar
 */
public class TelaAdicionarItensVendaForm extends javax.swing.JFrame {
    ProdutoTipoFornecedorBO produtoTipoFornecedorBO = new ProdutoTipoFornecedorBO();
    /**
     * Creates new form TelaAdicionarItensVenda
     */
    
      
    public TelaAdicionarItensVendaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdutosDisponiveis = new javax.swing.JLabel();
        lblPesquisarProduto = new javax.swing.JLabel();
        cbxOpcoesBuscaProduto = new javax.swing.JComboBox<>();
        txtPesquisarProduto = new javax.swing.JTextField();
        btnBuscarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutosDisponiveis = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblUnidades = new javax.swing.JLabel();
        jspQuantidade = new javax.swing.JSpinner();
        lblQtdeDesejada = new javax.swing.JLabel();
        lblSelecioneProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblProdutosDisponiveis.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lblProdutosDisponiveis.setText("Produtos disponíveis no estoque");

        lblPesquisarProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPesquisarProduto.setText("Pesquisar por:");

        cbxOpcoesBuscaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Codigo", "Tipo" }));

        txtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarProdutoKeyReleased(evt);
            }
        });

        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        tblProdutosDisponiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Descrição", "Tipo", "Preço unitário", "QTDE em estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutosDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosDisponiveisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutosDisponiveis);
        if (tblProdutosDisponiveis.getColumnModel().getColumnCount() > 0) {
            tblProdutosDisponiveis.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblUnidades.setText("Unidades*:");

        lblQtdeDesejada.setText("Insira a quantidade desejada");

        lblSelecioneProduto.setText("Selecione o produto abaixo para adicionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProdutosDisponiveis)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPesquisarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxOpcoesBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUnidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspQuantidade))
                            .addComponent(lblQtdeDesejada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelecioneProduto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblProdutosDisponiveis)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxOpcoesBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto))
                .addGap(21, 21, 21)
                .addComponent(lblSelecioneProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblQtdeDesejada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidades))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoKeyReleased
        try{

            if(cbxOpcoesBuscaProduto.getSelectedIndex() == 0){

                preencherTabelaProdutos(tblProdutosDisponiveis, produtoTipoFornecedorBO.buscarDescricaoProdutosDisponiveis(txtPesquisarProduto.getText().trim()));
            }

            if(cbxOpcoesBuscaProduto.getSelectedIndex() == 2){

                preencherTabelaProdutos(tblProdutosDisponiveis, produtoTipoFornecedorBO.buscarTiposProdutosDisponiveis(txtPesquisarProduto.getText().trim()));
            }

        } catch (SistemaFloriculturaException e) {

            Mensagem.msgErro(e.getMessage());

        }catch(Exception ex){

            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_txtPesquisarProdutoKeyReleased

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed

        try{

            if(cbxOpcoesBuscaProduto.getSelectedIndex() == 0){

                preencherTabelaProdutos(tblProdutosDisponiveis, produtoTipoFornecedorBO.buscarDescricaoProdutosDisponiveis(txtPesquisarProduto.getText().trim()));
            }

            if(cbxOpcoesBuscaProduto.getSelectedIndex() == 1){

                List<ProdutoTipoFornecedorJOIN> produtoTipoFornecedorJOINs = new ArrayList<>();

                produtoTipoFornecedorJOINs.add(produtoTipoFornecedorBO.buscarCodigoProdutosDisponivel(Integer.parseInt(txtPesquisarProduto.getText().trim())));
                preencherTabelaProdutos(tblProdutosDisponiveis,produtoTipoFornecedorJOINs);
            }

            if(cbxOpcoesBuscaProduto.getSelectedIndex() == 2){

                preencherTabelaProdutos(tblProdutosDisponiveis, produtoTipoFornecedorBO.buscarTiposProdutosDisponiveis(txtPesquisarProduto.getText().trim()));
            }

        } catch (SistemaFloriculturaException e) {

            Mensagem.msgErro(e.getMessage());

        }catch(Exception ex){

            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        List<Produto> produtos = new ArrayList<>();
        
        try{
            
            produtos.add(extrairItemProduto());
            
            verificarCodigo(produtos.get(0).getCodigo());
            
            adicionarItemsTblItemVendas(produtos);
            
            atualizarTxtTotalVenda();
            
        } catch (SistemaFloriculturaException e) {

            Mensagem.msgErro(e.getMessage());

        }catch(Exception ex){

            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        try{
            
            visibleUnidade(false);
            preencherTabelaProdutos(tblProdutosDisponiveis, produtoTipoFornecedorBO.buscarDescricaoProdutosDisponiveis(""));

        } catch (SistemaFloriculturaException e) {

            Mensagem.msgErro(e.getMessage());

        }catch(Exception ex){

            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_formComponentShown

    private void tblProdutosDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosDisponiveisMouseClicked
        visibleUnidade(true);
    }//GEN-LAST:event_tblProdutosDisponiveisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarItensVendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarItensVendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarItensVendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarItensVendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarItensVendaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox<String> cbxOpcoesBuscaProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jspQuantidade;
    private javax.swing.JLabel lblPesquisarProduto;
    private javax.swing.JLabel lblProdutosDisponiveis;
    private javax.swing.JLabel lblQtdeDesejada;
    private javax.swing.JLabel lblSelecioneProduto;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JTable tblProdutosDisponiveis;
    private javax.swing.JTextField txtPesquisarProduto;
    // End of variables declaration//GEN-END:variables


    private void preencherTabelaProdutos(JTable tabela, List<ProdutoTipoFornecedorJOIN> produtos) throws Exception {
        
        DefaultTableModel tabelaModel = getModelo(tabela);
        
        deletarRowsTabela(tabelaModel);

        for (ProdutoTipoFornecedorJOIN produto : produtos) {

            
            try {
                produto.getNomeTipo().equals("");
            } catch (NullPointerException e) {
                produto.setNomeTipo("Não especificado");
            }

            Object[] dados = {produto.getCodigo(),
                              produto.getDescricao(),
                              produto.getNomeTipo(),
                              produto.getValorVenda(),
                              produto.getQtde()
            };

            tabelaModel.addRow(dados);        
        }
    }
    
    private void visibleUnidade(boolean boll){
        
        lblQtdeDesejada.setVisible(boll);
        lblUnidades.setVisible(boll);
        jspQuantidade.setVisible(boll);
        jspQuantidade.setValue(1);
        btnAdicionar.setVisible(boll);
    }
    
    private Produto extrairItemProduto() throws Exception {
        
        Produto produto = new Produto();
        int linha = tblProdutosDisponiveis.getSelectedRow();
        
        produto.setIdFornecedor(-1);
        produto.setIdTipo(-1);
        
        if(linha != -1){
            
            produto.setCodigo(Integer.parseInt(tblProdutosDisponiveis.getValueAt(linha, 0).toString()));
            produto.setDescricao(tblProdutosDisponiveis.getValueAt(linha, 1).toString());
            produto.setValorVenda((float) tblProdutosDisponiveis.getValueAt(linha, 3));
           
            int qtde = Integer.parseInt(jspQuantidade.getValue().toString());
            
            if( qtde <= 0 || qtde > Integer.parseInt(tblProdutosDisponiveis.getValueAt(linha, 4).toString()))
                throw new QtdeUnitarioException();
            
            produto.setQtde((Integer) jspQuantidade.getValue());
            
        }else throw new LinhaSelectionException();
        
        return produto;
    }

}
