/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemaFloricultura.apresentacao;

import br.com.sistemaFloricultura.BO.TipoBO;
import br.com.sistemaFloricultura.entidade.Mensagem;
import br.com.sistemaFloricultura.entidade.Tipo;
import br.com.sistemaFloricultura.apresentacao.TelaPrincipalForm;
import br.com.sistemaFloricultura.excecao.CamposObrigatoriosException;
import br.com.sistemaFloricultura.excecao.LinhaSelectionException;
import br.com.sistemaFloricultura.excecao.SistemaFloriculturaException;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josemar
 */
public class TelaTipoForm extends javax.swing.JFrame {

    TipoBO tipoBO = new TipoBO();
    /**
     * Creates new form TelaTipo
     */
    public TelaTipoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormularioTipo = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        lblDescricaoTipo = new javax.swing.JLabel();
        lblFormulario = new javax.swing.JLabel();
        lblGerenciamentoTipo = new javax.swing.JLabel();
        pnlOpcoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipos = new javax.swing.JTable();
        lblTituloTabela = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de cadastro de Tipos");
        setName("tipoForm"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlFormularioTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDescricaoTipo.setText("Descrição*:");

        lblFormulario.setText("Formulário");

        javax.swing.GroupLayout pnlFormularioTipoLayout = new javax.swing.GroupLayout(pnlFormularioTipo);
        pnlFormularioTipo.setLayout(pnlFormularioTipoLayout);
        pnlFormularioTipoLayout.setHorizontalGroup(
            pnlFormularioTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioTipoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblDescricaoTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(pnlFormularioTipoLayout.createSequentialGroup()
                .addComponent(lblFormulario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFormularioTipoLayout.setVerticalGroup(
            pnlFormularioTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioTipoLayout.createSequentialGroup()
                .addComponent(lblFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlFormularioTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoTipo)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        lblGerenciamentoTipo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGerenciamentoTipo.setText("Gerencimento de tipo de produtos");

        pnlOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcoesLayout = new javax.swing.GroupLayout(pnlOpcoes);
        pnlOpcoes.setLayout(pnlOpcoesLayout);
        pnlOpcoesLayout.setHorizontalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOpcoesLayout.setVerticalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTipos);
        if (tblTipos.getColumnModel().getColumnCount() > 0) {
            tblTipos.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        lblTituloTabela.setText("Tabela de tipo de produtos cadastrados");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFormularioTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblGerenciamentoTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloTabela)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGerenciamentoTipo)
                .addGap(29, 29, 29)
                .addComponent(pnlFormularioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Tipo tipo = new Tipo();
        
        try{           
            
            verificarCamposObrigatorios();
            
            if (Mensagem.msgQuestionamento("Tem certeza que deseja cadastrar esse novo tipo?") == 0) {
                
            
                tipo = extrairPnlTipo();

                tipoBO.cadastrar(tipo);
                
                Mensagem.msgInformacao("Novo tipo cadastrado com sucesso!");
                
                preencherTabelaTipos(tblTipos, tipoBO.listar());
                
                txtDescricao.setText("");
            }
            
            
        } catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        dispose();
               
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int codigo;
        
        try{
            
            if(tblTipos.getSelectedRow() == -1)
                throw new LinhaSelectionException();
            
            if(Mensagem.msgQuestionamento("Tem certeza que deseja excluir esse tipo de produto?") == 0){
                
                codigo = extraiRowSelectedTblTipos().getCodigo();
                
                tipoBO.excluir(codigo);
                
                Mensagem.msgInformacao("Tipo de produto excluído com sucesso!");
                
                preencherTabelaTipos(tblTipos, tipoBO.listar());
                
                txtDescricao.setText("");
            }
            
        }catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Tipo tipo = new Tipo();
        
        try{           
            
            verificarCamposObrigatorios();
            
            if (Mensagem.msgQuestionamento("Tem certeza que deseja atualizar esse tipo?") == 0) {
                
            
                tipo = extrairPnlTipo();
                tipo.setCodigo(extraiRowSelectedTblTipos().getCodigo());

                tipoBO.atualizar(tipo);
                
                Mensagem.msgInformacao("Novo tipo atualizado com sucesso!");
                
                txtDescricao.setText("");
            }
            
            
        } catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        try{           
            
            preencherTabelaTipos(tblTipos, tipoBO.listar());
            
        } catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_formComponentShown

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        try{           
            
            preencherTabelaTipos(tblTipos, tipoBO.buscarNomes(txtDescricao.getText()));
            
        } catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiposMouseClicked
        
        try{           
            
            setFormulario(extraiRowSelectedTblTipos().getNome());
            
        } catch (SistemaFloriculturaException e) {
            
            Mensagem.msgErro(e.getMessage());
            
        }catch(Exception ex){
            
            ex.printStackTrace();
            Mensagem.msgErro("Erro!!! Exiba a seguinte mensagem para o administrador do sistema\n"+ex.getMessage());
        }
    }//GEN-LAST:event_tblTiposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTipoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTipoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTipoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTipoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTipoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricaoTipo;
    private javax.swing.JLabel lblFormulario;
    private javax.swing.JLabel lblGerenciamentoTipo;
    private javax.swing.JLabel lblTituloTabela;
    private javax.swing.JPanel pnlFormularioTipo;
    private javax.swing.JPanel pnlOpcoes;
    private javax.swing.JTable tblTipos;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables

    private void verificarCamposObrigatorios() {
        
        if(this.txtDescricao.getText().trim().equals("")){
            throw new CamposObrigatoriosException();
        }
    }
    
    private void setFormulario(String nome){
        txtDescricao.setText(nome);
    }

    private Tipo extrairPnlTipo() {
        Tipo tipo = new Tipo();
        
        tipo.setNome(this.txtDescricao.getText());
        
        return tipo;
    }
    
    private void preencherTabelaTipos(JTable tabela, List<Tipo> tipos) {
        
        DefaultTableModel tabelaModel = new TelaPrincipalForm().getModelo(tabela);
        
        new TelaPrincipalForm().deletarRowsTabela(tabelaModel);
        
        for (Tipo tipo : tipos) {
            
            Object[] dados = {tipo.getCodigo(),
                              tipo.getNome(),
            };
            
            tabelaModel.addRow(dados);
        }
    }
    
     private Tipo extraiRowSelectedTblTipos() {
        
        Tipo tipo = new Tipo();
        int linha = tblTipos.getSelectedRow();
        
        if(linha != -1){
            
            tipo.setCodigo(Integer.parseInt(tblTipos.getValueAt(linha, 0).toString()));
            tipo.setNome(tblTipos.getValueAt(linha, 1).toString());
            
        }else throw new LinhaSelectionException();
        
        return tipo;
    }
}
